```{r}
df <- read.csv("data_regressions/Chile_2021_flip.csv.gz", encoding = "UTF-8")
df <- na.omit(df)
df <- subset(df, rate_winner < 0.5)
df$country <- "France"
df$year <- 2017
df
```
Read multiple files
```{r}
library(stringr)

items <- list(c("France", 2017), c("France", 2022), c("Chile", 2017), c("Chile", 2021)) # , c("Romania", 2009)
df <- data.frame()
for(item in items) {
  country <- item[1]
  year <- item[2]
  
  path <- "data_regressions/${country}_${year}_flip.csv.gz"
  path <- stringr::str_interp(path, list(country=country, year=year))
  
  print(path)
  
  tmp <- read.csv(path, encoding = "UTF-8")
  tmp <- na.omit(tmp)
  tmp <- tmp[c("dv_loser", "dv_winner", "flip", "flip_neighbors", "en_winner", "en_loser", "rate_winner", "rate_loser", "en_dv_winner", "en_dv_loser", "polarization", "polling_winner_fround")]
  tmp$country <- country
  tmp$year <- year
  
  df <- rbind(df, tmp)
}
df <- subset(df, rate_winner < 0.5)
```


Libraries

```{r}
library(stargazer)
library(fixest)
library("bife")
library(spatialreg)
library(spdep)
library(alpaca)
```


```{r}
model.1 <- alpaca::feglm(
  flip ~ scale(rate_winner) + scale(rate_loser) | country + year,
  family = binomial(link = "logit"),
  data = df
)

model.2 <- alpaca::feglm(
  flip ~ scale(rate_winner) + scale(rate_loser) | department + country + year,
  family = binomial(link = "logit"),
  data = df
)

model.3 <- alpaca::feglm(
  flip ~ scale(dv_winner) + scale(dv_loser) | country + year,
  family = binomial(link = "logit"),
  data = df
)

model.4 <- alpaca::feglm(
  flip ~ scale(en_winner) + scale(en_loser) | country + year,
  family = binomial(link = "logit"),
  data = df
)

model.5 <- alpaca::feglm(
  flip ~ scale(en_dv_winner) + scale(en_dv_loser) | country + year,
  family = binomial(link = "logit"),
  data = df
)

model.6 <- alpaca::feglm(
  flip ~ scale(rate_winner) + scale(rate_loser) + scale(dv_winner) + scale(dv_loser) | country + year,
  family = binomial(link = "logit"),
  data = df
)

model.7 <- alpaca::feglm(
  flip ~ scale(rate_winner) + scale(rate_loser) + scale(dv_winner) + scale(dv_loser) + scale(en_winner) + scale(en_loser) | country + year,
  family = binomial(link = "logit"),
  data = df
)

model.8 <- alpaca::feglm(
  flip ~ scale(rate_winner) + scale(rate_loser) + scale(dv_winner) + scale(dv_loser) + scale(en_winner) + scale(en_loser) + scale(en_dv_winner) + scale(en_dv_loser) + scale(flip_neighbors) + scale(polling_winner_fround)  | country + year,
  family = binomial(link = "logit"),
  data = df
)

model.9 <- alpaca::feglm(
  flip ~ scale(rate_winner) + scale(rate_loser) + scale(dv_winner) + scale(dv_loser) + scale(en_winner) + scale(en_loser) + scale(en_dv_winner) + scale(en_dv_loser) + scale(polarization) + scale(flip_neighbors) + scale(polling_winner_fround)  | country + year,
  family = binomial(link = "logit"),
  data = df
)

# stargazer(model_1, model_2, model_3, model_4, model_5, model_6, type = "text") +  scale(flip_neighbors) 
```



```{r}
source("nlstargazer.R")
target <- c(
  "scale(rate_winner)",
  "scale(rate_loser)",
  "scale(dv_winner)",
  "scale(dv_loser)",
  "scale(en_winner)",
  "scale(en_loser)",
  "scale(en_dv_winner)",
  "scale(en_dv_loser)",
  #"scale(en_winner_2)",
  #"scale(en_loser_2)",
  #"scale(en_dv_winner_2)",
  #"scale(en_dv_loser_2)",
  "scale(polling_winner_fround)",
  "scale(flip_neighbors)",
  "scale(polarization)"
  # "scale(flip_neighbors)",
)
tbl <- nlstargazer(
  list(model.1, model.2, model.3, model.4, model.5, model.6, model.7, model.8, model.9),
  digits = 3,
  sort_parameters = target,
  rename_parameters = list(
    c("scale(rate_winner)", "Rate Winner"),
    c("scale(rate_loser)", "Rate Loser"),
    c("scale(dv_winner)", "Divisiveness Winner"),
    c("scale(dv_loser)", "Divisiveness Loser"),
    c("scale(en_winner)", "Endorsement Winner"),
    c("scale(en_loser)", "Endorsement Loser"),
    c("scale(en_dv_winner)", "Div. Endors. Winner"),
    c("scale(en_dv_loser)", "Div. Endors. Loser"),
    c("scale(polling_winner_fround)", "Same.Winner"),
    c("scale(flip_neighbors)", "Avg. Flip Neighbors"),
    c("scale(polarization)", "GPI")
  )
)

kable(tbl) %>%
  kable_classic_2(full_width = T)
```


```{r}
writeLines(knitr::kable(tbl, "latex") , 'df.tex')

```



```{r}
library(ShapleyValue)
y <- df$flip
x <- df[, c("rate_winner", "rate_loser", "dv_winner", "dv_loser", "en_winner", "en_loser", "flip_neighbors", "polling_winner_fround", "en_dv_winner", "en_dv_loser")]


shapleyvalue(y, x)

```
```{r}
library(caret)
varImp(model_1, scale = FALSE)

```

```{r}
library(jtools)
model <- glm(
  flip ~ scale(rate_winner) + scale(rate_loser),
  family = binomial(link = "logit"),
  data = df
)

plot_summs(model, plot.distributions = TRUE)
```

