---
title: "Appendix Regressions"
output: html_document
date: "2024-01-11"
---

```{r}
library(lfe)
library(plm)       # Panel data analysis library
library(sjPlot)
library(texreg)
library(jtools)
library(tidyverse)
library(bife)
```

## Including Plots

```{r}
vars <- list(
  "epi_1"="EP (t - 1)",
  "epi_between_1"="Between-EP (t - 1)",
  "epi_within_1"="Within-EP (t - 1)",
  "gini"="Inequality level (t)",
  "scale(gini)"="Inequality level (t)",
  "scale(theil)"="Inequality Theil (t)",
  "scale(atkin05)"="Inequality Atkin05 (t)",
  "gini_1"="Inequality level (t - 1)",
  "unemployment"="Unemployment (t)",
  "scale(unemployment)"="Unemployment (t)",
  "unemployment_1"="Unemployment (t - 1)",
  "scale(epi_within)"="Within-EP (t)",
  "scale(epi_between)"="Between-EP (t)",
  "scale(gini):scale(unemployment)"="Inequality * Unemployment (t)",
  "scale(unemployment):scale(gini)"="Inequality * Unemployment (t)",
  "scale(theil):scale(unemployment)"="Inequality * Unemployment (t)",
  "scale(unemployment):scale(theil)"="Inequality * Unemployment (t)",
  "scale(atkin05):scale(unemployment)"="Inequality * Unemployment (t)",
  "scale(unemployment):scale(atkin05)"="Inequality * Unemployment (t)",
  "scale(epi_lag)"="Polarization (t - 1)",
  "sp_epi_1"="Spatial EP (t - 1)",
  "sp_epi_between_1"="Spatial Between-EP (t - 1)",
  "sp_epi_within_1"="Spatial Within-EP (t - 1)",
  "scale(sp_epi_lag)"="Spatial polarization (t)",
  "scale(sp_epi_within)"="Spatial Within-EP (t)",
  "scale(sp_epi_between)"="Spatial Between-EP (t)",
  "scale(sp_epi)"="Spatial EP (t)",
  "sp_epi_1"="Spatial EP (t - 1)",
  "sp_epi"="Spatial EP (t)",
  "ed_attainment"="Ed. Attainment (t)",
  "scale(ed_attainment)"="Ed. Attainment (t)",
  "ed_attainment_1"="Ed. Attainment (t - 1)",
  "log(expenditure)"="Log of expenditure PC (t)",
  "scale(expenditure)"="Expenditure PC (t)",
  "log(expenditure_1)"="Expenditure PC (t - 1)",
  "log(personal_income)"="Log of personal Income PC (t)",
  "scale(personal_income)"="Personal Income PC (t)",
  "log(personal_income_1)"="Log of personal Income PC (t - 1)",
  "log(gdp)"="Log of GDP PC (t)",
  "scale(gdp)"="GDP PC (t)",
  "log(gdp_1)"="Log of GDP PC (t - 1)",
  "log(population)"="Log of population (t)",
  "scale(population)"="Population (t)",
  "log(population_1)"="Log of population (t - 1)",
  "log(pop_density + 1)"="Log of Pop. Density (t)",
  "scale(pop_density)"="Pop. Density (t)",
  "log(pop_density_1 + 1)"="Log of Pop. Density (t - 1)",
  "swing"="Swing State",
  "(Intercept)"="(Intercept)"
)

```

You can also embed plots, for example:

```{r}
df <- read.csv(file = "data_regressions/United_States_sociodemographic.csv")
df$swing <- df$type == "SWING"
df$gdp <- df$gdp / df$population

df
```

```{r}
model.1 <- felm(scale(ep) ~ scale(gini)  | year + swing | 0 | state, data = df)

model.2 <- felm(scale(ep) ~ scale(gini) + scale(unemployment) | year + swing | 0 | state, data = df)

model.3 <- felm(scale(ep) ~ scale(gini) + scale(unemployment)  + scale(gdp) + scale(pop_density) + scale(ed_attainment) | year + swing | 0 | state, data = df)

texreg(
  list(model.1, model.2, model.3),
  stars = c(0.01, 0.05, 0.1),
  caption="State-level association of EP in the United States (2008-2020). Each model represents a multivariate regression, with year-fixed effects. Standard errors are in brackets and are robustly clustered by state. We standardized both independent and dependent variables to have a mean of zero and a standard deviation of one.",
  custom.coef.map=vars,
  label="tab:ep"
)
```
```{r}
model.1 <- felm(scale(ec) ~ scale(gini)  | year + swing | 0 | state, data = df)

model.2 <- felm(scale(ec) ~ scale(gini) + scale(unemployment) | year + swing | 0 | state, data = df)

model.3 <- felm(scale(ec) ~ scale(gini) + scale(unemployment)  + scale(gdp) + scale(pop_density) + scale(ed_attainment) | year + swing | 0 | state, data = df)

texreg(
  list(model.1, model.2, model.3),
  stars = c(0.01, 0.05, 0.1),
  custom.coef.map=vars,
  caption="State-level association of EC in the United States (2008-2020). Each model represents a multivariate regression, with year-fixed effects. Standard errors are in brackets and are robustly clustered by state. We standardized both independent and dependent variables to have a mean of zero and a standard deviation of one.",
  label="tab:ec"
)
```

