---
title: "R Notebook"
output: html_notebook
---

```{r}
library(lfe)
library(plm)       # Panel data analysis library
library(stargazer)
library(sjPlot)
library(texreg)
library(jtools)
library(tidyverse)
library(bife)
source("nlstargazer.R")
source("customstargazer.R")
```


Reads a DataFrame for the United States (2000-2020)
```{r}
df <- read.csv(file = "data_regressions/United_States_sociodemographic.csv")
#df <- subset(df, state != "DISTRICT OF COLUMBIA")
#df <- subset(df, state != "HAWAII")
#df <- subset(df, state != "ALASKA")

#df <- subset(df, type == "SWING")

df$swing <- df$type == "SWING"
df$gdp <- df$gdp / df$population
df
```

Sets a list of variables 
```{r}
vars <- list(
  "epi_1"="EP (t - 1)",
  "epi_between_1"="Between-EP (t - 1)",
  "epi_within_1"="Within-EP (t - 1)",
  "gini"="Inequality level (t)",
  "scale(gini)"="Inequality level (t)",
  "scale(theil)"="Inequality Theil (t)",
  "scale(atkin05)"="Inequality Atkin05 (t)",
  "gini_1"="Inequality level (t - 1)",
  "unemployment"="Unemployment (t)",
  "scale(unemployment)"="Unemployment (t)",
  "unemployment_1"="Unemployment (t - 1)",
  "scale(epi_within)"="Within-EP (t)",
  "scale(epi_between)"="Between-EP (t)",
  "scale(gini):scale(unemployment)"="Inequality * Unemployment (t)",
  "scale(unemployment):scale(gini)"="Inequality * Unemployment (t)",
  "scale(theil):scale(unemployment)"="Inequality * Unemployment (t)",
  "scale(unemployment):scale(theil)"="Inequality * Unemployment (t)",
  "scale(atkin05):scale(unemployment)"="Inequality * Unemployment (t)",
  "scale(unemployment):scale(atkin05)"="Inequality * Unemployment (t)",
  "scale(epi_lag)"="Polarization (t - 1)",
  "sp_epi_1"="Spatial EP (t - 1)",
  "sp_epi_between_1"="Spatial Between-EP (t - 1)",
  "sp_epi_within_1"="Spatial Within-EP (t - 1)",
  "scale(sp_epi_lag)"="Spatial polarization (t)",
  "scale(sp_epi_within)"="Spatial Within-EP (t)",
  "scale(sp_epi_between)"="Spatial Between-EP (t)",
  "scale(sp_epi)"="Spatial EP (t)",
  "sp_epi_1"="Spatial EP (t - 1)",
  "sp_epi"="Spatial EP (t)",
  "ed_attainment"="Ed. Attainment (t)",
  "scale(ed_attainment)"="Ed. Attainment (t)",
  "ed_attainment_1"="Ed. Attainment (t - 1)",
  "log(expenditure)"="Log of expenditure PC (t)",
  "scale(expenditure)"="Expenditure PC (t)",
  "log(expenditure_1)"="Expenditure PC (t - 1)",
  "log(personal_income)"="Log of personal Income PC (t)",
  "scale(personal_income)"="Personal Income PC (t)",
  "log(personal_income_1)"="Log of personal Income PC (t - 1)",
  "log(gdp)"="Log of GDP PC (t)",
  "scale(gdp)"="GDP PC (t)",
  "log(gdp_1)"="Log of GDP PC (t - 1)",
  "log(population)"="Log of population (t)",
  "scale(population)"="Population (t)",
  "log(population_1)"="Log of population (t - 1)",
  "log(pop_density + 1)"="Log of Pop. Density (t)",
  "scale(pop_density)"="Pop. Density (t)",
  "log(pop_density_1 + 1)"="Log of Pop. Density (t - 1)",
  "swing"="Swing State",
  "(Intercept)"="(Intercept)"
)


#"epi_lag"
#colnames(data1)[colnames(data1) == "sp_epi"] ="sp_epi_lag"
```

Model for Voting Turnout

```{r}
model.1 = felm(scale(turnout) ~ scale(gini) + swing | year | 0 | state, data=df)

model.2 = felm(scale(turnout) ~ scale(unemployment) + swing | year | 0 | state, data=df)

model.3 = felm(scale(turnout) ~ scale(epi_within) + swing | year | 0 | state, data=df)

model.4 = felm(scale(turnout) ~ scale(epi_between) + swing | year | 0 | state, data=df)

model.5 = felm(scale(turnout) ~ scale(gini) + scale(unemployment) + scale(epi_within) + scale(epi_between) + scale(gini):scale(unemployment) + scale(ed_attainment) + scale(personal_income) + scale(gdp) + scale(pop_density) + swing | year | 0 | state, data=df)

model.6 = felm(scale(turnout) ~ scale(gini) + scale(unemployment) + scale(epi_within) + scale(epi_between) + scale(gini):scale(unemployment) + scale(sp_epi_between) + scale(sp_epi_within) + scale(ed_attainment) + scale(personal_income) + scale(gdp) + scale(pop_density) + swing | year | 0 | state, data=df)

tbl <- screenreg(
  list(model.1, model.2, model.3, model.4, model.5, model.6),
  caption="State-level association of Voting Turnout in the United States (2008-2020). Each model represents a multivariate regression, with year-fixed effects. Standard errors are in brackets and are robustly clustered by state. We standardized both independent and dependent variables to have a mean of zero and a standard deviation of one. Note: ***$p<0.01$, **$p<0.05$, *$p<0.1$.",
  label="tab:epi_1",
  stars = c(0.01, 0.05, 0.1),
  custom.coef.map=vars
)

tbl
```

Model for Political Polarization

```{r}
model.1 = felm(scale(polarization2) ~ scale(gini) + swing | year | 0 | state, data=df)

model.2 = felm(scale(polarization2) ~ scale(unemployment) + swing | year | 0 | state, data=df)

model.3 = felm(scale(polarization2) ~ scale(epi_within) + swing | year | 0 | state, data=df)

model.4 = felm(scale(polarization2) ~ scale(epi_between) + swing | year | 0 | state, data=df)

model.5 = felm(scale(polarization2) ~ scale(gini) + scale(unemployment) + scale(epi_within) + scale(epi_between) + scale(gini):scale(unemployment) + scale(ed_attainment) + scale(personal_income) + scale(gdp) + scale(pop_density) + swing | year | 0 | state, data=df)

model.6 = felm(scale(polarization2) ~ scale(gini) + scale(unemployment) + scale(epi_within) + scale(epi_between) + scale(gini):scale(unemployment) + scale(sp_epi_between) + scale(sp_epi_within) + scale(ed_attainment) + scale(personal_income) + scale(gdp) + scale(pop_density) + swing | year | 0 | state, data=df)

tbl <- texreg(
  list(model.1, model.2, model.3, model.4, model.5, model.6),
  caption="State-level association of Political Polarization in the United States (2008-2020). Each model represents a multivariate regression, with year-fixed effects. Standard errors are in brackets and are robustly clustered by state. We standardized both independent and dependent variables to have a mean of zero and a standard deviation of one. Note: ***$p<0.01$, **$p<0.05$, *$p<0.1$.",
  label="tab:epi_1",
  stars = c(0.01, 0.05, 0.1),
  custom.coef.map=vars
)

tbl
```



State-level regression analyses with year-fixed effects for EPI.

```{r}
model.1 <- felm(epi ~ epi_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.2 <- felm(epi ~ gini_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.3 <- felm(epi ~ unemployment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.4 <- felm(epi ~ sp_epi_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.5 <- felm(epi ~ ed_attainment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.6 <- felm(epi ~ log(personal_income_1) + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.7 <- felm(epi ~ gini_1 + log(personal_income_1) + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.8 <- felm(epi ~ epi_1 + gini_1 + log(personal_income_1) + sp_epi_1 + unemployment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.9 <- felm(epi ~ epi_1 + gini_1 + ed_attainment_1 + log(personal_income_1) + sp_epi_1 + unemployment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)

# 


tbl <- texreg(
  list(model.1, model.2, model.3, model.4, model.5, model.6, model.7, model.8, model.9),
  caption="State-level regression analyses of EP as dependent variable. Each regression includes period-fixed effects. Standard errors in brackets. Note: ***$p<0.01$, **$p<0.05$, *$p<0.1$.",
  label="tab:epi_1",
  stars = c(0.01, 0.05, 0.1),
  custom.coef.map=vars
)

writeLines(tbl, "Latex_Tables/EPI.tex")

screenreg(
  list(model.1, model.2, model.3, model.4, model.5, model.6, model.7, model.8, model.9),
  caption="State-level regression analyses of EP as dependent variable. Each regression includes period-fixed effects. Standard errors in brackets. Note: ***$p<0.01$, **$p<0.05$, *$p<0.1$.",
  label="tab:epi_1",
  stars = c(0.01, 0.05, 0.1),
  custom.coef.map=vars
)
```

qs


```{r}
model.1 <- felm(epi_between ~ epi_between_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.2 <- felm(epi_between ~ gini_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.3 <- felm(epi_between ~ unemployment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.4 <- felm(epi_between ~ sp_epi_between_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.5 <- felm(epi_between ~ ed_attainment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.6 <- felm(epi_between ~ log(personal_income_1) + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.7 <- felm(epi_between ~ gini_1 + log(personal_income_1) + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.8 <- felm(epi_between ~ epi_between_1 + gini_1 + log(personal_income_1) + sp_epi_between_1 + unemployment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.9 <- felm(epi_between ~ epi_between_1 + gini_1 + ed_attainment_1 + log(personal_income_1) + sp_epi_between_1 + unemployment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)

#

tbl <- texreg(
  list(model.1, model.2, model.3, model.4, model.5, model.6, model.7, model.8, model.9),
  caption="State-level regression analyses of Between-EP as dependent variable. Each regression includes period-fixed effects. Standard errors in brackets. Note: ***$p<0.01$, **$p<0.05$, *$p<0.1$.",
  label="tab:between_epi_1",
  stars = c(0.01, 0.05, 0.1),
  custom.coef.map=vars
)

writeLines(tbl, "Latex_Tables/Between-EPI.tex")

screenreg(
  list(model.1, model.2, model.3, model.4, model.5, model.6, model.7, model.8, model.9),
  caption="State-level regression analyses of Between-EP as dependent variable. Each regression includes period-fixed effects. Standard errors in brackets. Note: ***$p<0.01$, **$p<0.05$, *$p<0.1$.",
  label="tab:between_epi_1",
  stars = c(0.01, 0.05, 0.1),
  custom.coef.map=vars
)
```

```{r}
model.1 <- felm(epi_within ~ epi_within_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.2 <- felm(epi_within ~ gini_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.3 <- felm(epi_within ~ unemployment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.4 <- felm(epi_within ~ sp_epi_within_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.5 <- felm(epi_within ~ ed_attainment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.6 <- felm(epi_within ~ log(personal_income_1) + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.7 <- felm(epi_within ~ gini_1 + log(personal_income_1) + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.8 <- felm(epi_within ~ epi_within_1 + gini_1 + log(personal_income_1) + sp_epi_within_1 + unemployment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.9 <- felm(epi_within ~ epi_within_1 + gini_1 + ed_attainment_1 + log(personal_income_1) + sp_epi_within_1 + unemployment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)

#

tbl <- texreg(
  list(model.1, model.2, model.3, model.4, model.5, model.6, model.7, model.8, model.9),
  caption="State-level regression analyses of Within-EP as dependent variable. Each regression includes period-fixed effects. Standard errors in brackets. Note: ***$p<0.01$, **$p<0.05$, *$p<0.1$.",
  label="tab:within_epi_1",
  stars = c(0.01, 0.05, 0.1),
  custom.coef.map=vars
)

writeLines(tbl, "Latex_Tables/Within-EPI.tex")

```


```{r}
model.1 <- felm(epi ~ gini_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.2 <- felm(epi ~ unemployment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.3 <- felm(epi ~ sp_epi_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.4 <- felm(epi ~ ed_attainment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.5 <- felm(epi ~ log(personal_income_1) + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.6 <- felm(epi ~ gini_1 + log(personal_income_1) + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.7 <- felm(epi ~ gini_1 + log(personal_income_1) + sp_epi_1 + unemployment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.8 <- felm(epi ~ gini_1 + ed_attainment_1 + log(personal_income_1) + sp_epi_1 + unemployment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)


#

tbl <- texreg(
  list(model.1, model.2, model.3, model.4, model.5, model.6, model.7, model.8),
  caption="State-level regression analyses of EP as dependent variable. Each regression includes period-fixed effects. Standard errors in brackets. Note: ***$p<0.01$, **$p<0.05$, *$p<0.1$.",
  label="tab:epi_3",
  stars = c(0.01, 0.05, 0.1),
  custom.coef.map=vars
)

writeLines(tbl, "Latex_Tables/EPI-v2.tex")
```


```{r}
model.1 <- felm(epi_between ~ gini_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.2 <- felm(epi_between ~ unemployment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.3 <- felm(epi_between ~ sp_epi_between_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.4 <- felm(epi_between ~ ed_attainment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.5 <- felm(epi_between ~ log(personal_income_1) + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.6 <- felm(epi_between ~ gini_1 + log(personal_income_1) + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.7 <- felm(epi_between ~ gini_1 + log(personal_income_1) + sp_epi_between_1 + unemployment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.8 <- felm(epi_between ~ gini_1 + ed_attainment_1 + log(personal_income_1) + sp_epi_between_1 + unemployment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)

#
tbl <- texreg(
  list(model.1, model.2, model.3, model.4, model.5, model.6, model.7, model.8),
  caption="State-level regression analyses of Between-EP as dependent variable. Each regression includes period-fixed effects. Standard errors in brackets. Note: ***$p<0.01$, **$p<0.05$, *$p<0.1$.",
  label="tab:between_epi_3",
  stars = c(0.01, 0.05, 0.1),
  custom.coef.map=vars
)

writeLines(tbl, "Latex_Tables/Between-EPI-v2.tex")
```


```{r}
model.1 <- felm(epi_within ~ gini_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.2 <- felm(epi_within ~ unemployment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.3 <- felm(epi_within ~ sp_epi_within_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.4 <- felm(epi_within ~ ed_attainment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.5 <- felm(epi_within ~ log(personal_income_1) + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.6 <- felm(epi_within ~ gini_1 + log(personal_income_1) + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.7 <- felm(epi_within ~ gini_1 + log(personal_income_1) + sp_epi_within_1 + unemployment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)
model.8 <- felm(epi_within ~ gini_1 + ed_attainment_1 + log(personal_income_1) + sp_epi_within_1 + unemployment_1 + log(gdp_1) + log(pop_density_1 + 1) | year | 0 | state, data = df)


# 

tbl <- texreg(
  list(model.1, model.2, model.3, model.4, model.5, model.6, model.7, model.8),
  caption="State-level regression analyses of Within-EP as dependent variable. Each regression includes period-fixed effects. Standard errors in brackets. Note: ***$p<0.01$, **$p<0.05$, *$p<0.1$.",
  label="tab:within_epi_3",
  stars = c(0.01, 0.05, 0.1),
  custom.coef.map=vars
)

writeLines(tbl, "Latex_Tables/Within-EPI-v2.tex")
```

Regression analysis
```{r}

# EPI
data1 <- df
colnames(data1)[colnames(data1) == "epi"] ="epi_d"
colnames(data1)[colnames(data1) == "epi_1"] ="epi_lag"
colnames(data1)[colnames(data1) == "sp_epi"] ="sp_epi_lag"

model.1 <- felm(scale(epi_d) ~ scale(gini) + scale(ed_attainment) + scale(personal_income) + scale(gdp) + scale(pop_density) | state | 0 | state, data = data1)

model.2 <- felm(scale(epi_d) ~ scale(unemployment) + scale(ed_attainment) + scale(personal_income) + scale(gdp) + scale(pop_density) | state | 0 | state, data = data1)

model.3 <- felm(scale(epi_d) ~ scale(gini) + scale(unemployment) + scale(ed_attainment) + scale(personal_income) + scale(gdp) + scale(pop_density) | state | 0 | state, data = data1)

model.4 <- felm(scale(epi_d) ~ scale(gini) + scale(unemployment) + scale(ed_attainment) + scale(epi_lag) + scale(sp_epi_lag) + scale(personal_income) + scale(gdp) + scale(pop_density) | state | 0 | state, data = data1)

# Within-EPI
data2 <- df

colnames(data2)[colnames(data2) == "epi_within"] ="epi_d"
colnames(data2)[colnames(data2) == "epi_within_1"] ="epi_lag"
colnames(data2)[colnames(data2) == "sp_epi_within"] ="sp_epi_lag"

model.5 <- felm(scale(epi_d) ~ scale(gini) + scale(ed_attainment) + scale(personal_income) + scale(gdp) + scale(pop_density) | state | 0 | state, data = data2)

model.6 <- felm(scale(epi_d) ~ scale(unemployment) + scale(ed_attainment) + scale(personal_income) + scale(gdp) + scale(pop_density) | state | 0 | state,  data = data2)

model.7 <- felm(scale(epi_d) ~ scale(gini) + scale(unemployment) + scale(ed_attainment) + scale(personal_income) + scale(gdp) + scale(pop_density) | state | 0 | state, data = data2)

model.8 <- felm(scale(epi_d) ~ scale(gini) + scale(unemployment) + scale(ed_attainment) + scale(epi_lag) + scale(sp_epi_lag) + scale(personal_income) + scale(gdp) + scale(pop_density) | state | 0 | state, data = data2)

# Between-EPI
data3 <- df
colnames(data3)[colnames(data3) == "epi_between"] ="epi_d"
colnames(data3)[colnames(data3) == "epi_between_1"] ="epi_lag"
colnames(data3)[colnames(data3) == "sp_epi_between"] ="sp_epi_lag"

model.9 <- felm(scale(epi_d) ~ scale(gini) + scale(ed_attainment) + scale(personal_income) + scale(gdp) + scale(pop_density) | state | 0 | state, data = data3)

model.10 <- felm(scale(epi_d) ~ scale(unemployment) + scale(ed_attainment) + scale(personal_income) + scale(gdp) + scale(pop_density) | state | 0 | state, data = data3)

model.11 <- felm(scale(epi_d) ~ scale(gini) + scale(unemployment) + scale(ed_attainment) + scale(personal_income)+ scale(gdp) + scale(pop_density) | state | 0 | state, data = data3)

model.12 <- felm(scale(epi_d) ~ scale(gini) + scale(unemployment) + scale(ed_attainment) + scale(epi_lag) + scale(sp_epi_lag) + scale(personal_income) + scale(gdp) + scale(pop_density) | state | 0 | state, data = data3)

    #c("State F.E.", " ", "✓", "✓", "✓", " ", "✓", "✓", "✓", " ", "✓","✓", "✓"),
    #c("Year F.E.", " ", "✓", "✓", "✓", " ", "✓", "✓", "✓", " ", "✓","✓", "✓")
  

tbl <- screenreg(
  list(model.1, model.2, model.3, model.4, model.5, model.6, model.7, model.8, model.9, model.10, model.11, model.12),
  caption="State-level association of Election Polarization in the United States (2000-2020). Each model represents a multivariate regression, with year and state fixed effects. Standard errors in brackets. We standardized both independent and dependent variables to have a mean of zero and a standard deviation of one. Note: $***p<0.01$, $**p<0.05$, $*p<0.1$.",
  label="tab:epi_regressions",
  stars = c(0.01, 0.05, 0.1),
  custom.coef.map=vars
)

writeLines(tbl, "Latex_Tables/polarization-manuscript.tex")
tbl
```

```{r}
cor(df[c("personal_income", "gini", "gdp", "pop_density", "unemployment")])
```



```{r}
model <- felm(epi_between_r ~ gini_r + unemployment_r + gdp_r, data = df)

screenreg(model, stars = c(0.01, 0.05, 0.1))
```




```{r}
# EPI
data1 <- df
colnames(data1)[colnames(data1) == "epi_1"] ="epi_lag"
colnames(data1)[colnames(data1) == "epi"] ="epi_d"
colnames(data1)[colnames(data1) == "sp_epi_1"] ="sp_epi_d_1"

model.1 <- felm(scale(epi_d) ~ scale(gini_1) + scale(expenditure_1) + scale(personal_income_1) + scale(unemployment_1) + scale(population_1) + scale(gdp_1) | year | 0 | state, data = data1)

model.2 <- felm(scale(epi_d) ~ scale(gini_1) + scale(expenditure_1) + scale(personal_income_1) + scale(sp_epi_d_1) + scale(unemployment_1) + scale(population_1) + scale(gdp_1) | year | 0 | state, data = data1)

model.3 <- felm(scale(epi_d) ~ scale(gini_1) + scale(expenditure_1) + scale(personal_income_1) + scale(epi_lag) + scale(sp_epi_d_1) + scale(unemployment_1) + scale(population_1) + scale(gdp_1) | year | 0 | state, data = data1)

# Within-EPI
data2 <- df

colnames(data2)[colnames(data2) == "epi_within"] ="epi_d"
colnames(data2)[colnames(data2) == "sp_epi_within_1"] ="sp_epi_d_1"
colnames(data2)[colnames(data2) == "epi_within_1"] ="epi_lag"

model.4 <- felm(scale(epi_d) ~ scale(gini_1) + scale(expenditure_1) + scale(personal_income_1) + scale(unemployment_1) + scale(population_1) + scale(gdp_1) | year | 0 | state, data = data2)

model.5 <- felm(scale(epi_d) ~ scale(gini_1) + scale(expenditure_1) + scale(personal_income_1) + scale(sp_epi_d_1) + scale(unemployment_1) + scale(population_1) + scale(gdp_1) | year | 0 | state, data = data2)

model.6 <- felm(scale(epi_d) ~ scale(gini_1) + scale(expenditure_1) + scale(personal_income_1) + scale(epi_lag) + scale(sp_epi_d_1) + scale(unemployment_1) + scale(population_1) + scale(gdp_1) | year | 0 | state, data = data2)

# Between-EPI
data3 <- df
colnames(data3)[colnames(data3) == "epi_between"] ="epi_d"
colnames(data3)[colnames(data3) == "sp_epi_between_1"] ="sp_epi_d_1"
colnames(data3)[colnames(data3) == "epi_between_1"] ="epi_lag"

model.7 <- felm(scale(epi_d) ~ scale(gini_1) + scale(expenditure_1) + scale(personal_income_1) + scale(unemployment_1) + scale(population_1) + scale(gdp_1) | year | 0 | state, data = data3)

model.8 <- felm(scale(epi_d) ~ scale(gini_1) + scale(expenditure_1) + scale(personal_income_1) + scale(sp_epi_d_1) + scale(unemployment_1) + scale(population_1) + scale(gdp_1) | year | 0 | state, data = data3)

model.9 <- felm(scale(epi_d) ~ scale(gini_1) + scale(expenditure_1) + scale(personal_income_1) + scale(epi_lag) + scale(sp_epi_d_1) + scale(unemployment_1) + scale(population_1) + scale(gdp_1) | year | 0 | state, data = data3)

screenreg(
  list(model.1, model.2, model.3, model.4, model.5, model.6, model.7, model.8, model.9),
  caption="County-level regressions for small counties. The dependent variable is the Net flow.",
  label="tab:small_county",
  stars = c(0.01, 0.05, 0.1),
  custom.coef.map=vars
)
```


Associations of EPI with more variables


```{r}
model.1 <- felm(epi_between ~ epi_between_1 + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.2 <- felm(epi_between ~ gini + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.3 <- felm(epi_between ~ unemployment + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.4 <- felm(epi_between ~ sp_epi_between + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.5 <- felm(epi_between ~ ed_attainment + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.6 <- felm(epi_between ~ log(personal_income) + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.7 <- felm(epi_between ~ gini + log(personal_income) + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.8 <- felm(epi_between ~ epi_between_1 + gini +  log(personal_income) + sp_epi_between + unemployment + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.9 <- felm(epi_between ~ epi_between_1 + gini + ed_attainment + log(personal_income) + sp_epi_between + unemployment + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)



tbl <- texreg(
  list(model.1, model.2, model.3, model.4, model.5, model.6, model.7, model.8, model.9),
  caption="State-level regression analyses of Between-EP as dependent variable. Each regression includes period-fixed effects. Standard errors in brackets. Note: ***$p<0.01$, **$p<0.05$, *$p<0.1$.",
  label="tab:between_epi_2",
  stars = c(0.01, 0.05, 0.1),
  custom.coef.map=vars
)

writeLines(tbl, "Latex_Tables/Between-EPI-current.tex")
```

Within-EPI
```{r}
model.1 <- felm(epi_within ~ epi_within_1 + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.2 <- felm(epi_within ~ gini + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.3 <- felm(epi_within ~ unemployment + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.4 <- felm(epi_within ~ sp_epi_within + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.5 <- felm(epi_within ~ ed_attainment + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.6 <- felm(epi_within ~ log(personal_income) + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.7 <- felm(epi_within ~ gini + log(personal_income) + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.8 <- felm(epi_within ~ epi_within_1 + gini + log(personal_income) + sp_epi_within + unemployment + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.9 <- felm(epi_within ~ epi_within_1 + gini + ed_attainment + log(personal_income) + sp_epi_within + unemployment + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)

tbl <- texreg(
  list(model.1, model.2, model.3, model.4, model.5, model.6, model.7, model.8, model.9),
  caption="State-level regression analyses of Within-EP as dependent variable. Each regression includes period-fixed effects. Standard errors in brackets. Note: ***$p<0.01$, **$p<0.05$, *$p<0.1$.",
  label="tab:within_epi_2",
  stars = c(0.01, 0.05, 0.1),
  custom.coef.map=vars
)

writeLines(tbl, "Latex_Tables/Within-EPI-current.tex")

```




EPI

Within-EPI
```{r}
model.1 <- felm(epi ~ epi_1 + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.2 <- felm(epi ~ gini + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.3 <- felm(epi ~ unemployment + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.4 <- felm(epi ~ sp_epi + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.5 <- felm(epi ~ ed_attainment + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.6 <- felm(epi ~ log(personal_income) + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.7 <- felm(epi ~ gini + log(personal_income) + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.8 <- felm(epi ~ epi_1 + gini + log(personal_income) + sp_epi + unemployment + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)
model.9 <- felm(epi ~ epi_1 + gini + ed_attainment + log(personal_income) + sp_epi + unemployment + log(gdp) + log(pop_density + 1) | year | 0 | state, data = df)


tbl <- texreg(
  list(model.1, model.2, model.3, model.4, model.5, model.6, model.7, model.8, model.9),
  caption="State-level regression analyses of EP as dependent variable. Each regression includes period-fixed effects. Standard errors in brackets. Note: ***$p<0.01$, **$p<0.05$, *$p<0.1$.",
  label="tab:epi_2",
  stars = c(0.01, 0.05, 0.1),
  custom.coef.map=vars
)

writeLines(tbl, "Latex_Tables/EPI-current.tex")

```