---
title: "R Notebook"
output: html_notebook
---

```{r}
library(data.table)
library(lfe)
library(jtools)
library(stargazer)
library(minpack.lm)
source("nlstargazer.r")
```


Read file generated in Python
```{r}
df <- fread("data_output/regression_Chile_2021.csv")
df <- subset(df, candidate == "JOSE ANTONIO KAST RIST") # 
df
```


Run OLS Regression Models
```{r}
model_1 <- lm(rate ~ rate_parisi + rate_kast + rate_meo + rate_sichel + rate_provoste, data = df)
model_2 <- lm(rate ~ divisiveness_parisi + divisiveness_kast + divisiveness_meo + divisiveness_sichel + divisiveness_provoste, data = df)
model_3 <- lm(rate ~ rate_parisi + rate_kast + rate_meo + rate_sichel + rate_provoste + divisiveness_parisi + divisiveness_kast + divisiveness_meo + divisiveness_sichel + divisiveness_provoste, data = df)

stargazer(model_1, model_2, model_3, type = "text")

```



```{r}
model_1 <- nlsLM(
    formula = rate ~ const + b_parisi*rate_parisi + b_kast*rate_kast + b_meo*rate_meo + b_sichel*rate_sichel + b_provoste*rate_provoste,
    data = df, 
    start = list(const=0, b_parisi=0, b_kast=0, b_meo=0, b_sichel=0, b_provoste=0),
    lower = c(const=-Inf, b_parisi=0, b_kast=0, b_meo=0, b_sichel=0, b_provoste=0),
    upper = c(const=Inf, b_parisi=1, b_kast=1, b_meo=1, b_sichel=1, b_provoste=1),
    algorithm = "port",
    model = FALSE
)

model_2 <- nlsLM(
    formula = rate ~ const + d_parisi*divisiveness_parisi + d_kast*divisiveness_kast + d_meo*divisiveness_meo + d_sichel*divisiveness_sichel + d_provoste*divisiveness_provoste,
    data = df, 
    start = list(const=0, d_parisi=0, d_kast=0, d_meo=0, d_sichel=0, d_provoste=0)
)

model_3 <- nlsLM(
    formula = rate ~ const + b_parisi*rate_parisi + b_kast*rate_kast + b_meo*rate_meo + b_sichel*rate_sichel + b_provoste*rate_provoste + d_parisi*divisiveness_parisi + d_kast*divisiveness_kast + d_meo*divisiveness_meo + d_sichel*divisiveness_sichel + d_provoste*divisiveness_provoste,
    data = df, 
    start = list(const=0, b_parisi=0, b_kast=0, b_meo=0, b_sichel=0, b_provoste=0, d_parisi=0, d_kast=0, d_meo=0, d_sichel=0, d_provoste=0),
    lower = c(const=-Inf, b_parisi=0, b_kast=0, b_meo=0, b_sichel=0, b_provoste=0, d_parisi=-Inf, d_kast=-Inf, d_meo=-Inf, d_sichel=-Inf, d_provoste=-Inf),
    upper = c(const=Inf, b_parisi=1, b_kast=1, b_meo=1, b_sichel=1, b_provoste=1, d_parisi=Inf, d_kast=Inf, d_meo=Inf, d_sichel=Inf, d_provoste=Inf)
)

models <- list(model_1, model_2, model_3)
nlstargazer(models = models)

```
```{r}

```

```{r}
data1r <- fread("data_output/Chile/2021_first_round.csv.gz")
data_1r <- data1r[ , .(value = sum(value)), by = candidate]
data_1r$rate <- data_1r$value / sum(data_1r$value)
data_1r
```


```{r}
candidates <- c(subset(data_1r, rate > 0.02)[["candidate"]])
candidates
```



```{r}
coefs <- coef(model_1)
df_model <- data.table(
  candidate = c("JOSE ANTONIO KAST RIST", "YASNA PROVOSTE CAMPILLAY", "SEBASTIAN SICHEL RAMIREZ", "MARCO ENRIQUEZ-OMINAMI GUMUCIO", "FRANCO PARISI FERNANDEZ"),
  coef = c(coefs[["b_kast"]], coefs[["b_provoste"]], coefs[["b_sichel"]], coefs[["b_meo"]], coefs[["b_parisi"]])
)
df_model <- merge(df_model, data_1r, all=TRUE)
df_model[["1_coef"]] <- 1 - df_model$coef


df_model[["to_candidate_a"]] <- df_model[["rate"]] * df_model[["coef"]]
df_model[["to_candidate_b"]] <- df_model[["rate"]] * df_model[["1_coef"]]

df_model
```
```{r}
draw_sankey(df_model, candidates)
```



```{r}
source <- c()
target <- c()
value <- c()

idx_candidate_a <- length(candidates) + 0
idx_candidate_b <- length(candidates) + 1

for(i in 1:nrow(df_model)) {
  row <- df_model[i, ]
  candidate <- row[["candidate"]]
  idx <- which(candidates == candidate)[1] - 1

  if (!(is.na(row[["coef"]]))) {
    print(candidate)
    source <- append(source, idx)
    target <- append(target, idx_candidate_a) # BORIC
    value <- append(value, row[["to_candidate_b"]] * 100)
    
    source <- append(source, idx)
    target <- append(target, idx_candidate_b) # KAST
    value <- append(value, row[["to_candidate_a"]] * 100)
  }

  else if (candidate == "GABRIEL BORIC FONT") {
    source <- append(source, idx)
    target <- append(target, idx_candidate_a) # BORIC
    value <- append(value, row[["rate"]] * 100)
    
    source <- append(source, idx)
    target <- append(target, idx_candidate_b) # KAST
    value <- append(value, 0)
  }
  
}
```

```{r}
# Load the package required to read JSON files.
library("rjson")
# Give the input file name to the function.
colors <- fromJSON(file="consts.json")
# Print the result.
print(colors[["FRANCO PARISI FERNANDEZ"]])

label <- c(candidates, c("GABRIEL BORIC FONT", "JOSE ANTONIO KAST RIST"))
color_label <- c()

for (x in label) {
  color_label <- append(color_label, colors[[x]])
}

color_label
```


```{r}
library(plotly)

fig <- plot_ly(
    type = "sankey",
    orientation = "h",

    node = list(
      label = label,
      color = color_label,
      pad = 15,
      thickness = 20,
      line = list(
        color = "black",
        width = 0
      )
    ),

    link = list(
      source = source,
      target = target,
      value =  value,
      color = "#ebebeb"
    )
  )
fig <- fig %>% layout(
    title = "",
    font = list(
      size = 16
    )
)

fig
```

